name: Synopsys Detect scan for released code
on:
  push:
    tags: 
      - '*'
jobs:
    security:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        - name: Run Synopsys Detect
          uses: fnxpt/blackduck-action@main
          with:
            hubURL: ${{ secrets.BLACKDUCK_URL }}
            hubToken: ${{ secrets.BLACKDUCK_TOKEN }}
            projectType: ios
            projectName: test-github
            version: ${{ steps.get_version.outputs.VERSION }}
