name: Synopsys Detect scan for latest code
on:
  push:
    branches:    
      - 'main'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Synopsys Detect
      uses: fnxpt/blackduck-action@main
      with:
          hubURL: ${{ secrets.BLACKDUCK_URL }}
          hubToken: ${{ secrets.BLACKDUCK_TOKEN }}
          projectType: ios
          projectName: test-github
